# -*- coding: utf-8 -*-
"""risk_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/190WV7Gvl2ZybzwPabKP8ZSOHmpuSSvjX
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

crypto_df = pd.read_csv("/content/crypto-markets.csv")
crypto_df.head()

crypto_df = crypto_df[crypto_df['date'].str.startswith("2018")]
crypto_df = crypto_df[crypto_df['date'] != "2018-11-30"]
crypto_df['daily_returns'] = (crypto_df['close'] - crypto_df['open']) / (crypto_df['open']) * 100
crypto_df.head()

bc_df = crypto_df[crypto_df['name'] == "Bitcoin"]
ax = sns.scatterplot(x = 'open', y = 'close', data = bc_df)
ax.set(xlabel = "Opening Price per Day for Bitcoin", ylabel = "Closing Price per Day for Bitcoin", 
       title = "Opening Price vs Closing Price daily")
plt.show()

plt.plot(bc_df['date'], bc_df['daily_returns'])
plt.xlabel('Date')
plt.ylabel('Daily Returns for Bitcoin Stock')
plt.title('Daily Returns for Bitcoin')
plt.show()